# 사용자 정의 속성
profile:
  value: 'test'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/updb  # ${TEST_DB_URL}
    username: sh
    password: sh
    driver-class-name: com.mysql.cj.jdbc.Driver

coolsms:
  api:
    key: ${SMS_KEY}
    secret: ${SMS_SECRET}

sns:
  naver:
    key: ${NAVER_KEY}
    secret: ${NAVER_SECRET}
  kakao:
    key: ${KAKAO_KEY}
    secret: ${KAKAO_SECRET}
  google:
    key: ${GOOGLE_KEY}
    secret: ${GOOGLE_SECRET}