# 사용자 정의 속성
profile:
  value: 'prod'

spring:
  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

coolsms:
  api:
    key: ${SMS_KEY}
    secret: ${SMS_SECRET}

sns:
  naver:
    key: ${NAVER_KEY}
    secret: ${NAVER_SECRET}
  kakao:
    key: ${KAKAO_KEY}
    secret: ${KAKAO_SECRET}

server:
  servlet:
    context-path: /app